qyang-nj/llios

- macho_parser/sources/code_signature.c
Add CDHash and print hash algorithm
> [Mach-O Parser] Improve code signature parsing

- README.md
- macho_parser/.gitignore
- macho_parser/README.md
- macho_parser/build.sh
- macho_parser/build_sample.sh
- macho_parser/docs/LC_CODE_SIGNATURE.md
- macho_parser/sources/argument.c
- macho_parser/sources/argument.h
- macho_parser/sources/build_version.c
- macho_parser/sources/code_signature.c
- macho_parser/sources/dyld_info.c
- macho_parser/sources/dysymtab.c
- macho_parser/sources/linkedit_data.c
- macho_parser/sources/main.c
- macho_parser/sources/segment_64.c
- macho_parser/sources/symtab.c
Optimize command arguments logic
> [Mach-O Parser] Optimize command arguments 

- README.md
- macho_parser/README.md
- macho_parser/docs/LC_SYMTAB.md
- macho_parser/sources/symtab.c
Move LC_SYMTAB to its own doc.
> [Mach-O Parser] LC_SYMTAB

- README.md
- macho_parser/README.md
- macho_parser/build.sh
- macho_parser/docs/LC_DYSYMTAB.md
- macho_parser/sources/argument.c
- macho_parser/sources/argument.h
- macho_parser/sources/dysymtab.c
- macho_parser/sources/macho_header.c
- macho_parser/sources/macho_header.h
- macho_parser/sources/main.c
- macho_parser/sources/symtab.c
- macho_parser/sources/symtab.h
- macho_parser/sources/util.c
- macho_parser/sources/util.h
* Separate `LC_DYSYMTAB` to it's own doc
* polish the logic of `LC_DYSYMTAB`
> [Mach-O Parser] LC_DYSYMTAB

- README.md
- dynamic_linking/BindingInfo.md
- dynamic_linking/docs/BindingInfo.md
- macho_parser/docs/LC_DYLD_INFO.md
Document binding information in `LC_DYLD_INFO(_ONLY)`.
> [Dynamic Linking] Add doc for binding info

- macho_parser/README.md
- macho_parser/sources/argument.c
- macho_parser/sources/argument.h
- macho_parser/sources/macho_header.cpp
Add `--arch` option to support selecting architecture.
> [Mach-O Parser] Support selecting architecture

- README.md
- dynamic_linking/chained_fixups.md
- macho_parser/README.md
- macho_parser/sources/chained_fixups.cpp
- macho_parser/sources/chained_fixups.h
- macho_parser/sources/linkedit_data.c
Update the doc and code about LC_DYLD_CHAINED_FIXUPS
> [Mach-O Parser] Update LC_DYLD_CHAINED_FIXUPS

- macho_parser/sources/argument.c
- macho_parser/sources/argument.h
- macho_parser/sources/macho_header.cpp
> [Mach-O Header] Improve parsing mach-o header

- README.md
- macho_parser/README.md
- macho_parser/docs/LC_ENCRYPTION_INFO.md
- macho_parser/sources/argument.c
- macho_parser/sources/encryption_info.cpp
- macho_parser/sources/encryption_info.h
- macho_parser/sources/main.cpp
Parse `LC_ENCRYPTION_INFO_64` and add notes for it.
> [Mach-O Parser] Add LC_ENCRYPTION_INFO_64

- README.md
- macho_parser/README.md
- macho_parser/docs/LC_MAIN.md
- macho_parser/sources/argument.c
- macho_parser/sources/main.cpp
- macho_parser/sources/small_cmds.cpp
- macho_parser/sources/small_cmds.h
Parse `LC_MAIN` and add notes for it.
> [Mach-O Parser] Add LC_MAIN

- macho_parser/README.md
- macho_parser/build.sh
- macho_parser/docs/LC_CODE_SIGNATURE.md
- macho_parser/sources/code_signature.c
- macho_parser/sources/code_signature.cpp
- macho_parser/sources/code_signature.h
- macho_parser/sources/linkedit_data.c
- convert `code_signature.c` to cpp
- add notes for App Store resigning
> [Mach-O Parser] Update LC_CODE_SIGNATURE

- README.md
- macho_parser/README.md
- macho_parser/build_sample.sh
- macho_parser/docs/LC_DYLD_ENVIRONMENT.md
- macho_parser/sources/argument.c
- macho_parser/sources/main.cpp
- macho_parser/sources/small_cmds.cpp
- Parse LC_DYLD_ENVIRONMENT
- use -dyld_env in the sample
- add doc for LC_DYLD_ENVIRONMENT
> [Mach-O Parser] Parse LC_DYLD_ENVIRONMENT

- build_ios_app/README.md
- build_ios_app/Sources/AppDelegate.swift
- build_ios_app/Sources/DynamicLib/DynamicLib.swift
- build_ios_app/Sources/ObjcDylib/LLIOSObjcDylib.h
- build_ios_app/Sources/ObjcDylib/LLIOSObjcDylib.m
- build_ios_app/Sources/ObjcDylib/module.modulemap
- build_ios_app/Sources/SwiftDylib/SwiftDylib.swift
- build_ios_app/Sources/ViewController.swift
- build_ios_app/build.sh
- build_ios_app/launch.sh
* add an example of building ObjC dylib
* refactor the build script
> [Build iOS App] Add an ObjC dylib

- README.md
- macho_parser/README.md
- macho_parser/docs/LC_LINKER_OPTION.md
- macho_parser/sources/argument.c
- add LC_LINKER_OPTION
- improve
> [Mach-O Parser] add LC_LINKER_OPTION

- macho_parser/docs/LC_SYMTAB.md
- macho_parser/sources/argument.cpp
- macho_parser/sources/argument.h
- macho_parser/sources/macho_binary.h
- macho_parser/sources/symtab.cpp
* Added support of parsing STAB symbol
> [Mach-O Parser] Enhace symtab parsing

- build_ios_app/Sources/MixedModule/MySwiftMaterial.swift
Demonstrate how access modifier, inheritance and @objc annotation affect Objc interface generation.
> Demonstrate how objc interfaces are generated

- dynamic_linking/README.md
- dynamic_linking/build.sh
- build x86_64 arch
- update README.md
> [dynamic_linking] update build script and doc

- README.md
- articles/ModuleMap.md
Add notes about what I learned about module map
> Add notes about modulemap

- .github/workflows/main.yml
- macho_parser/.bazelrc
- macho_parser/BUILD.bazel
- macho_parser/WORKSPACE.bazel
- macho_parser/sources/dyld_info.cpp
- macho_parser/sources/exports_trie.cpp
- macho_parser/sources/linkedit_data.c
- macho_parser/sources/util.c
- macho_parser/sources/util.h
- macho_parser/sources/utils/leb128.cpp
- macho_parser/sources/utils/utils.h
- macho_parser/tests/leb128.cpp
* Moved LEB128 functions to utils
* Added some unit tests
> [Macho Parser] Move LEB128 functions to utils

- testing/code_coverage/Lib.swift
- testing/code_coverage/Test.swift
- testing/code_coverage/build_and_test.sh
Add a sample for building and running code coverage
> Add a sample for building and running code coverage

- macho_parser/sources/segment_64.cpp
- macho_parser/sources/util.c
- macho_parser/sources/util.h
- macho_parser/sources/utils/formatting.cpp
- macho_parser/sources/utils/utils.h
- macho_parser/tests/formatting.cpp
Implemented `formatSize` in c++ and added some tests.
> [MachO Parser] Format Size

- README.md
- articles/BuildSwiftMacros.md
- building/swift_macros/.gitignore
- building/swift_macros/Package.resolved
- building/swift_macros/Package.swift
- building/swift_macros/StringifyMacro.swift
- building/swift_macros/main.swift
* Documented how to build Swift Macros
* Added a sample to build with SPM
> Document how to build Swift Macros

- articles/SwiftModule.md
This repo is so great! Thanks for documenting everything you've discovered in here.
> Fix up past/present tense.
